# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Create Zip
      - name: Create Zip
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: .
          filename: 'resourcepack.zip'
          exclusions: '*.md *.txt *.psd *.rtf'
      
      # Generate SHA1
      - name: Generate SHA1
        id: hashgen
        uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha1
          get-assets: true
      - name: Echo
        run: |
          echo "SHA1 hashes:"
          echo ${{ steps.hashgen.output.hashes }}
      - name : SHA1 to file
        uses: DamianReeves/write-file-action@master
        with:
          path: hashes.txt
          contents: ${{ steps.hashgen.output.hashes }}
          write-mode: overwrite
      
      - name: Upload pack
        uses: JasonEtco/upload-to-release@master
        with:
          args: resourcepack.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload hashes
        uses: JasonEtco/upload-to-release@master
        with:
          args: hashes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
