# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Tag'
        required: true
        
  push:
    tags:
    - '*'

env:
  GITHUB_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Create Zip
      - name: Create Zip
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: .
          filename: 'resourcepack.zip'
          exclusions: '*.md *.txt *.psd *.rtf'
      
      - name: Get Release Info
        id: release-info
        uses: jossef/action-latest-release-info@v1.2.0
      
      # Create Release
      - name: Upload Resource Pack zip
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-info.outputs.upload_url }}
          asset_path: resourcepack.zip
          asset_name: resourcepack.zip
          asset_content_type: application/zip

