# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Tag'
        required: true
        
  push:
    tags:
    - '*'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Create Zip
      - name: Create Zip
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: .
          filename: 'resourcepack.zip'
          exclusions: '*.md *.txt *.psd *.rtf'
      
      # Create Release
      - name: Upload Resource Pack zip
        uses: actions/upload-artifact@v3
        with:
          name: Resource Pack
          path: resourcepack.zip

