# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: read|write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Create Zip
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: 'releases/resourcepack.zip'
          exclusions: '*.md *.txt *.psd *.rtf'
      
      # Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "releases/resourcepack.zip"
          bodyFile: "releases/resourcepack.zip"

